package your.pack

import org.springframework.boot.context.properties.ConfigurationProperties
import org.springframework.stereotype.Component
import org.springframework.validation.annotation.Validated

@Component // Based on https://www.baeldung.com/configuration-properties-in-spring-boot. However, contrary to that page, we DO need @Component even with Spring Boot 2.2!
@ConfigurationProperties(prefix = "validateconfig")
@Validated
// For non-abstract open class, KOTLIN generates getValue(), setValue(String), but as FINAL!
//abstract class
//interface
open class ConfKotlin {
    private var _value: String? = null
    var value: String?
        get() = _value
        set(given) { _value = given }
}

@Component
@ConfigurationProperties(prefix = "validateconfig")
@Validated
open class ConfKotlinAutogenerated {
    var value: String?=null
    var another: String?=null
}
